# Generated by Django 3.2.16 on 2022-12-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords_x', models.FloatField(default=0, verbose_name='x座標')),
                ('coords_y', models.FloatField(default=0, verbose_name='y座標')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
