# Generated by Django 3.2.17 on 2023-03-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230327_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='click_Height',
            field=models.FloatField(default=0, verbose_name='クリック時のHeight'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='click_Width',
            field=models.FloatField(default=0, verbose_name='クリック時のWidth'),
        ),
    ]
