# Generated by Django 3.2.17 on 2023-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230327_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='click_mark',
            field=models.CharField(default='&#128147;', max_length=50, verbose_name='クリック時のマーク'),
        ),
    ]
