# Generated by Django 3.2.17 on 2023-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_coordinates_click_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='click_mark',
            field=models.ImageField(upload_to='mark/'),
        ),
    ]
